//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipments_of_building_materials_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int Id { get; set; }
        public System.DateTime DealTime { get; set; }
        public int MaterialId { get; set; }
        public int NumOfMaterials { get; set; }
        public string CustomerName { get; set; }
        public double TotalCost { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
